[env]
# TERM = "xterm-256color"

[font]
size = 13

[font.glyph_offset]
x = 0
y = 8

[font.offset]
x = 0
y = 16

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "~/.local/scripts/env-launch.sh"]

[window.padding]
x = 0
y = 0

[window]
option_as_alt = 'Both'

# # Nightfox Alacritty Colors
# ## name: terafox
# ## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/terafox/alacritty.toml
#
# [colors.primary]
# background = "#1C1C1C"
# foreground = "#cbd9d8"
# dim_foreground = "#cbd9d8"
# bright_foreground = "#eaeeee"
#
# [colors.cursor]
# text = "#e6eaea"
# cursor = "#cbd9d8"
#
# [colors.vi_mode_cursor]
# text = "#e6eaea"
# cursor = "#a1cdd8"
#
# [colors.search.matches]
# foreground = "#e6eaea"
# background = "#425e5e"
#
# [colors.search.focused_match]
# foreground = "#e6eaea"
# background = "#7aa4a1"
#
# [colors.footer_bar]
# foreground = "#e6eaea"
# background = "#254147"
#
# [colors.hints.start]
# foreground = "#e6eaea"
# background = "#ff8349"
#
# [colors.hints.end]
# foreground = "#e6eaea"
# background = "#254147"
#
# [colors.selection]
# text = "#e6eaea"
# background = "#293e40"
#
# [colors.normal]
# black = "#2f3239"
# red = "#e85c51"
# green = "#7aa4a1"
# yellow = "#fda47f"
# blue = "#5a93aa"
# magenta = "#ad5c7c"
# cyan = "#a1cdd8"
# white = "#ebebeb"
#
# [colors.bright]
# black = "#4e5157"
# red = "#eb746b"
# green = "#8eb2af"
# yellow = "#fdb292"
# blue = "#73a3b7"
# magenta = "#b97490"
# cyan = "#afd4de"
# white = "#eeeeee"
#
# [colors.dim]
# black = "#282a30"
# red = "#c54e45"
# green = "#688b89"
# yellow = "#d78b6c"
# blue = "#4d7d90"
# magenta = "#934e69"
# cyan = "#89aeb8"
# white = "#c8c8c8"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#ff8349"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#cb7985"

# Nightfox Alacritty Colors
## name: carbonfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/alacritty.toml

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"
dim_foreground = "#b6b8bb"
bright_foreground = "#f9fbff"

[colors.cursor]
text = "#f2f4f8"
cursor = "#b6b8bb"

[colors.vi_mode_cursor]
text = "#f2f4f8"
cursor = "#33b1ff"

[colors.search.matches]
foreground = "#f2f4f8"
background = "#525253"

[colors.search.focused_match]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.footer_bar]
foreground = "#f2f4f8"
background = "#353535"

[colors.hints.start]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.hints.end]
foreground = "#f2f4f8"
background = "#353535"

[colors.selection]
text = "#f2f4f8"
background = "#2a2a2a"

[colors.normal]
black = "#282828"
red = "#ee5396"
green = "#25be6a"
yellow = "#08bdba"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"

[colors.bright]
black = "#484848"
red = "#f16da6"
green = "#46c880"
yellow = "#2dc7c4"
blue = "#8cb6ff"
magenta = "#c8a5ff"
cyan = "#52bdff"
white = "#e4e4e5"

[colors.dim]
black = "#222222"
red = "#ca4780"
green = "#1fa25a"
yellow = "#07a19e"
blue = "#6690d9"
magenta = "#a27fd9"
cyan = "#2b96d9"
white = "#bebebe"

[[colors.indexed_colors]]
index = 16
color = "#3ddbd9"

[[colors.indexed_colors]]
index = 17
color = "#ff7eb6"

